---
version: "2.0"
services:
  catfi-node:
    image: catfi/replicator:g{{.Generation}}
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
profiles:
  compute:
    catfi-node:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
